name: dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  animated_sidebar: ^1.0.1
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_ui_auth: ^1.14.0
  firebase_ui_oauth_google: ^1.3.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.4
  google_sign_in: ^6.2.1
  riverpod_annotation: ^2.3.5
  sidebarx: ^0.17.1
  syncfusion_flutter_calendar: ^25.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.10

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env